# Generated by Django 4.2.8 on 2023-12-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
