# Generated by Django 4.2.8 on 2023-12-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_state_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=50)),
                ('message', models.CharField(default='', max_length=300)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
